DOMAIN = "deye_modbus"

CONF_HOST = "host"
CONF_PORT = "port"
CONF_SLAVE = "slave"
CONF_SCAN_INTERVAL = "scan_interval"
CONF_INVERTER = "inverter"

DEFAULT_HOST = "10.10.20.102"
DEFAULT_PORT = 8899
DEFAULT_SLAVE = 1
DEFAULT_SCAN_INTERVAL = 10
DEFAULT_INVERTER = "deye_sun8k_sg05lp3"
